import Head from "next/head";
import Image from "next/image";
import { LoginForm } from "src/modules/profile";

export default function Login() {
  return (
    <>
      <Head>
        <title>Kanban App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen items-center justify-center ">
        <div className="container mx-auto flex flex-col items-center justify-center gap-8 px-8 md:flex-row">
          <Image
            priority
            src="/Home.svg"
            height={480}
            width={480}
            alt="Login"
          />
          <LoginForm />
        </div>
      </div>
    </>
  );
}
