import Head from "next/head";
import Image from "next/image";
import { LinkButton } from "src/components/LinkButton";
import { RegisterForm } from "src/modules/profile";

export default function Login() {
  return (
    <>
      <Head>
        <title>Kanban App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen items-center justify-center ">
        <div className="container mx-auto flex flex-col items-center justify-center gap-16 px-8 lg:flex-row">
          <Image
            priority
            src="/Home.svg"
            height={480}
            width={480}
            alt="Login"
          />
          <div className="w-full">
            <RegisterForm />
            <div className="mt-3">
              <LinkButton direction="/login">
                {"Already have an account? Log in here."}
              </LinkButton>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
