import Head from "next/head";

export const PublicMeta = () => {
  return (
    <Head>
      <title>Kanban</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/FavIcon.svg" />
    </Head>
  );
};
